services:
  jupyter:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: cardiac-sense-ci:latest
    container_name: jupyter
    restart: always
    tty: true
    ports:
      - 8888:8888
    volumes:
      - ./:/app
    working_dir: /app
