services:
  cardiac-sense-ci:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: cardiac-sense-ci:latest
    container_name: cardiac-sense
    restart: always
    tty: true
    ports:
      - 8888:8888
      - 8050:8050
    volumes:
      - ./:/app
    working_dir: /app
